# Generated by Django 5.0.3 on 2024-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.IntegerField(default=0),
        ),
    ]
